# EE569 Homework Assignment #2
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 11 Oct 2015
# Compiled on Mac with g++

all:
	g++ -o run main_sobel.cpp
	@echo "compiling the code"
	@echo "usage : ./run inputImageName outputImageName outputImageName outputImageName outputImageName outputImageName outputImageName"
	@echo "example : ./run Cougar.raw grayCougar.raw GradientCougar.raw Edge10Cougar.raw Non-Maximal10Cougar.raw Edge15Cougar.raw Non-Maximal15Cougar.raw"
	@echo "PLEASE ENTER YOUR FILE NAMES AS SHOWN IN THE ABOVE EXAMPLE"
