# EE569 Homework Assignment #2
# Name : Amruta Kulkarni
# USC ID : 6914-9708-27
# email : arkulkar@usc.edu
# Date : 11 Oct 2015
# Compiled on Mac with g++

all:
	g++ -o run main_canny.cpp
	@echo "compiling the code"
	@echo "usage : ./run inputImageName outputImageName outputImageName outputImageName outputImageName outputImageName"
	@echo "example : ./run Farm.raw edge1Farm.raw edge2Farm.raw edge3Farm.raw edge4Farm.raw edge5Farm.raw"
	@echo "PLEASE ENTER YOUR FILE NAMES AS SHOWN IN THE ABOVE EXAMPLE"
